config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'login'  => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users, expect: [:index, :destroy] do
    resources :relationships, only: [:create, :destroy]
  end
  resources :words, only: [:index, :create]
  resources :categories, only: [:index] do
    resources :lessons, only: [:create, :show, :new]
  end

  namespace :admins do
    root 'categories#index'
    resources :categories do
      resources :words, except: [:show, :index]
    end
    resources :users
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      activities = PublicActivity::Activity.order('created_at DESC')
      @activities = activities.paginate page: params[:page], per_page: 20
      @count = Word.word_user(current_user).count
    end
  end
end

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>
  <h1>Activites</h1>
  <div class="container">
    <p>
      <%= link_to "Lessons", "#", class: "btn btn-primary btn-lg" %>
      <%= link_to "Words", words_path, class: "btn btn-primary btn-lg active" %>
    </p>
    <div class="col-md-4">
      <section>
        <h2><%= gravatar_for current_user %></h2>
      </section>
      <section class="stats">
        <%= current_user.name %> <br/>
        Learned <%= @count %> words
      </section>
    </div>
    <div class="col-md-8">
      <%= will_paginate @activities %>
      <ul class="list-group">
        <% @activities.each do |activity| %>
          <%= render_activity activity, display: :i18n %>
        <% end %>
      </ul>
      <%= will_paginate @activities %>
    </div>
  </div>
<% else %>
  <div class="jumbotron center">
    <h1>Framgia E-Learning System</h1>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  <%= link_to image_tag("http://i.imgur.com/UV6trd2.jpg") %>
<% end %>