config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'login'  => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users, expect: [:index, :destroy] do
    resources :relationships, only: [:create, :destroy]
  end
  resources :words, only: [:index, :create]
  resources :categories, only: [:index] do
    resources :lessons, only: [:create, :show, :new]
  end

  namespace :admins do
    root 'categories#index'
    resources :categories do
      resources :words, except: [:show, :index]
    end
    resources :users
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, uniqueness: true, length: {maximum: 50}, presence: true
  validates :description, presence: true

  has_many :words, dependent: :destroy
  has_many :lessons
  accepts_nested_attributes_for :words, :lessons, allow_destroy: true
end

app/controllers/admins/categories_controller.rb
class Admins::CategoriesController < ApplicationController
  before_action :admin_user

  def index
    @categories = Category.paginate page: params[:page], per_page: 10
  end

  def show
    @category = Category.find params[:id]
    @words = @category.words.paginate page: params[:page], per_page: 10
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find params[:id]
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "Category #{@category.name} created!"
      redirect_to admins_category_path @category.id
    else
      render "new"
    end
  end

  def update
    @category = Category.find params[:id]
    if @category.update_attributes category_params
      flash[:success] = "Category update"
      redirect_to admins_category_path @category.id
    else
      render "edit"
    end
  end

  def destroy
    category = Category.find params[:id]
    flash[:success] = "Category #{category.name} delete"
    category.destroy
    redirect_to admins_categories_path
  end

  private

  def category_params
    params.require(:category).permit :name, :description
  end

  def admin_user
    redirect_to root_path unless isadmin?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logined_in_user

  def index
    @categories = Category.paginate page: params[:page], per_page: 5
  end
end

app/views/admins/categories/_category_fields.html.erb
<%= f.label :name %>
<%= f.text_field :name, class: "form-control field_info" %>
<%= f.label :description %>
<%= f.text_area :description, class: "form-control field_info" %>

app/views/admins/categories/edit.html.erb
<% provide(:title, "Edit Category") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <h1 class="account_info">Update <%= @category.name %> </h1>
    <%= form_for [:admins, @category] do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= render 'category_fields',f: f %>
      <%= f.submit "Save changes", class: "btn btn-primary btn_commit" %>
    <% end %>
  </div>
</div>

app/views/admins/categories/index.html.erb
<% provide(:title, "Categories") %>
<%= link_to "Create New Category", new_admins_category_path, class: "btn btn-primary pull-right" %>
<h1>All categories</h1>
<%= will_paginate %>
<ul class="users">
  <ul class="categories list-group">
  <% @categories.each do |category| %>
    <li id="category-<%= category.id %>">
      <span class="list-group-item">
        <%= link_to category.name, admins_category_path(category.id)%>
        <%= link_to "Delete", admins_category_path(category.id), method: :delete, class: "btn btn-danger pull-right" %>
        <%= link_to "Update", edit_admins_category_path(category.id), class: "btn btn-primary pull-right" %>
      </span>
    </li>
  <% end %>
  </ul>
</ul>
<%= will_paginate %>

app/views/admins/categories/new.html.erb
<% provide(:title, "New Category") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>New Category</h1>
    <%= form_for [:admins, @category] do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= render 'category_fields',f: f %>
      <%= f.submit "Create", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admins/categories/show.html.erb
<% provide(:title, @category.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h3><%= @category.name %></h3>
      <p><%= @category.description %></p>
      <%= link_to "New Word", new_admins_category_word_path(@category.id), class: "btn btn-primary" %>
      <%= link_to "Update", admins_category_path(@category.id), class: "btn btn-primary" %>
      <%= link_to "Delete", admins_category_path(@category.id), method: :delete, class: "btn btn btn-danger" %>
    </section>
  </aside>
</div>
<%= will_paginate @words %>
<div class="row">
  <% if @category.words.any? %>
    <%= render 'admins/words/word_table', category: @category, words: @words %>
  <% end %>
</div>
<%= will_paginate @words %>