config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'login'  => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users, expect: [:index, :destroy] do
    resources :relationships, only: [:create, :destroy]
  end
  resources :words, only: [:index, :create]
  resources :categories, only: [:index] do
    resources :lessons, only: [:create, :show, :new]
  end

  namespace :admins do
    root 'categories#index'
    resources :categories do
      resources :words, except: [:show, :index]
    end
    resources :users
  end

end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :results

  accepts_nested_attributes_for :results
  accepts_nested_attributes_for :answers,
                                reject_if: lambda {|a| a[:content].blank?},
                                allow_destroy: true

  validates :content, uniqueness: {scope: [:category_id]}
  validates :content, presence: true

  scope :word_user, -> user {joins(results: :lesson).where(lessons: {user_id: user}).distinct}
  scope :random_word, -> {limit(5).order('RAND()')}
  scope :learned, ->user, category_id {where(id: filter_all(user, category_id)).joins(results: :lesson).where(
                            lessons: {user_id: user}).distinct}

  scope :not_learned, ->user, category_id {where(id: filter_all(user, category_id)).where.not id: learned(user, category_id).map(&:id)}
  scope :filter_all, ->user, category_id {where category_id: category_id if(category_id && category_id.to_i != 0)}
end

app/controllers/admins/words_controller.rb
class Admins::WordsController < ApplicationController
  before_action :admin_user, except: [:show, :index]

  def new
    @category = Category.find params[:category_id]
    @word = Word.new
  end

  def edit
    @category = Category.find params[:category_id]
    @word = Word.find params[:id]
  end

  def create
    @category = Category.find params[:category_id]
    @word = Word.new word_params
    if @word.save
      redirect_to admins_category_path @category
    else
      render 'new'
    end
  end

  def update
    @category = Category.find params[:category_id]
    @word = Word.find params[:id]
    if @word.update_attributes word_params
      flash[:success] = "Word updated"
      redirect_to admins_category_url @category
    else
      render 'edit'
    end
  end

  def destroy
    word = Word.find params[:id]
    word.destroy
    flash[:success] = "Word #{word.content} deleted"
    redirect_to admins_category_path word.category
  end

  private
  
  def admin_user
    redirect_to root_path unless isadmin?
  end

  def word_params
    params.require(:word).permit :content, :category_id,
                          answers_attributes: [:id, :content, :correct, :_destroy]
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  before_action :logined_user, only: [:index, :create]

  def index
    @categories = Category.all
    params[:filter] = 'filter_all' if params[:filter].blank?
    @words = Word.send "#{params[:filter]}", *[current_user, params[:category_id]]
    respond_to do |format|
      format.html
      format.js
      format.pdf do
        pdf = WordPdf.new @words
        send_data pdf.render, filename: 'word_list.pdf', type: 'application/pdf'
      end
    end
  end

  private
  def logined_user
    redirect_to root_path unless logged_in?
  end
end

app/views/admins/words/_answer_fields.html.erb
<%= javascript_include_tag 'custom', 'data-turbolinks-track' => true %>
<div class="answer">
  <%= f.label :content, "Answer" %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", "#", class: 'remove-answer', remote: true %>
  <%= f.hidden_field :id, value: f.object.id %>
  <%= f.text_field :content, class: "form-control", required: true %>
  <%= f.label :correct, class: "checkbox" do %>
    <%= f.check_box :correct, onchange: "check(this)" %>
  <% end %>
</div>

app/views/admins/words/_word_fields.html.erb
<%= javascript_include_tag 'custom', 'data-turbolinks-track' => true %>
<div class="word">
  <%= f.label :content, "Word" %>
  <%= f.hidden_field :category_id, value: category.id %>
  <%= f.text_field :content, class: "form-control word_content" %>

  <div class="answers">
    <%= f.fields_for :answers do |builder| %>
      <%= render 'answer_fields', f: builder %>
    <% end %>
  </div>

  <p><%= create_add_answer_button "Add Answer", f, :answers %></p>
</div>

app/views/admins/words/_word_table.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Word</th>
      <th>Answer</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% words.each do |word| %>
      <tr>
        <td><%= word.id %></td>
        <td><%= word.content %></td>
        <td>
          <ol>
            <% word.answers.each do |a| %>
              <li>
                <%= a.content %>
                <% if a.correct? %>
                  <span class="btn glyphicon glyphicon-ok alert-success"></span>
                <% end %>
              </li>
            <% end %>
          </ol>
        </td>
        <td>
          <%= link_to "Edit", edit_admins_category_word_path(category, word), class: "btn btn-primary" %> &nbsp
          <%= link_to "Delete", admins_category_word_path(category, word), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admins/words/edit.html.erb
<% provide(:title,"Edit this lesson") %>

<div class="row" >
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit this lesson</h1>
    <%= form_for [:admins, @category, @word] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :content %>
      <%= f.text_field :content, class: "form-control" %>

      <div class="answers">
        <%= f.fields_for :answers do |builder| %>
          <%= render 'answer_fields', f: builder %>
        <% end %>
      </div>

      <p class="answer"><%= create_add_answer_button "Add answer", f, :answers %></p>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admins/words/new.html.erb
<% provide(:title,"Create new word") %>

<div class="row" >
  <div class="col-md-6 col-md-offset-3">
    <h1>Create new word</h1>
    <p>
      <b>Category Name:</b> <%= link_to @category.name, admins_category_path(@category) %>
    </p>
    <%= form_for [:admins, @category, @word] do |f|%>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="words">
        <%= fields_for @word do |builder| %>
          <%= render 'word_fields', f: builder, category: @category%>
        <% end %>
      </div>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>