config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'login'  => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users, expect: [:index, :destroy] do
    resources :relationships, only: [:create, :destroy]
  end
  resources :words, only: [:index, :create]
  resources :categories, only: [:index] do
    resources :lessons, only: [:create, :show, :new]
  end

  namespace :admins do
    root 'categories#index'
    resources :categories do
      resources :words, except: [:show, :index]
    end
    resources :users
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  ADMIN = 1

  attr_accessor :remember_token

  before_save {email.downcase!}

  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  validates :password, length: {minimum: 6}, allow_blank: true

  has_many :lessons, dependent: :destroy
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_secure_password

  accepts_nested_attributes_for :lessons

  def follow other_user
    active_relationships.create followed_id: other_user.id
  end

  def unfollow other_user
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following? other_user
    following.include? other_user
  end

  def User.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? remember_token
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attributes! remember_digest: nil
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :admin_user

  def index
    @users = User.paginate page: params[:page], per_page: 10
  end

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find params[:id]
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Create user success!"
      redirect_to admins_user_path @user
    else
      render "new"
    end
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes user_params
      flash[:success] = "User update"
      redirect_to admins_user_path @user
    else
      render "edit"
    end
  end

  def destroy
    user = User.find params[:id]
    user.destroy
    flash[:success] = "User #{user.name} delete"
    redirect_to admins_users_path
  end

  private

  def admin_user
    redirect_to root_path unless isadmin?
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = "Welcome to FELS !"
      redirect_to @user
    else
      render "new"
    end
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes user_params
      flash[:success] = "Profile update"
      redirect_to @user
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def correct_user
    @user = User.find params[:id]
    redirect_to root_path unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {size: 100})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/admins/users/edit.html.erb
<% provide(:title, "Edit User") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <h1 class="account_info">Update <%= @user.name %> </h1>
    <%= form_for [:admins, @user] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :role %>
      <%= f.check_box :role %>

      <%= f.submit "Save changes", class: "btn btn-primary btn_commit" %>
    <% end %>
  </div>
</div>

app/views/admins/users/index.html.erb
<% provide(:title, "All users") %>
<%= link_to "Create New User", new_admins_user_path, class: "btn btn-primary pull-right" %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <ul class="categories list-group">
  <% @users.each do |user| %>
    <% unless current_user?(user) %>
      <li id="user-<%= user.id %>">
        <%= gravatar_for user, size: 50 %>
        <%= link_to user.name, admins_user_path(user.id)%>
        <%= link_to "Delete", admins_user_path(user.id), method: :delete, class: "btn btn-danger pull-right" %>
        <%= link_to "Update", edit_admins_user_path(user.id), class: "btn btn-primary pull-right" %>
      </li>
    <% end %>
  <% end %>
  </ul>
</ul>

<%= will_paginate %>

app/views/admins/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admins, @user] do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <%= f.label :role %>
      <%= f.radio_button :role, false %>

      <%= f.submit "Create account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admins/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>